### ISSUE TITLE
TimeoutError: Timeout waiting for tab.goto

### ISSUE THREAD

**Issue by janisblaus** [ulixee/secret-agent#255] opened 2021-06-01 10:21 UTC
This timeout is given when trying to load two pages after each other using server/client setup, but it works when running directly.

How to reproduce:
1. run core server and client as separate scripts
2. Open google.com with await agent.goto('https://google.com/');
3. wait for the page to be loaded, painted
4. Open twitter.com with await agent.goto('https://twitter.com/');
5. timeout is given only **for second page** in about 30 seconds

this works as expected when a connection to the core is not used tho.

OS: windows 10
Node: 16.1
Secret agent: v1.4.1-alpha.5

here is trace:

`TimeoutError: Timeout waiting for "tab.goto(https://twitter.com/)"
    at Timer.waitForPromise (C:\projects\agent\node_modules\@secret-agent\commons\Timer.js:49:25)
    at Tab.goto (C:\projects\agent\node_modules\@secret-agent\core\lib\Tab.js:248:21)
    at CommandRecorder.runCommandFn (C:\projects\agent\node_modules\@secret-agent\core\lib\CommandRecorder.js:41:31)
    at Tab.CommandRecorder.owner.<computed> [as goto] (C:\projects\agent\node_modules\@secret-agent\core\lib\CommandRecorder.js:12:49)
    at ConnectionToClient.executeCommand (C:\projects\agent\node_modules\@secret-agent\core\server\ConnectionToClient.js:216:37)
    at ConnectionToClient.handleRequest (C:\projects\agent\node_modules\@secret-agent\core\server\ConnectionToClient.js:49:31)
    at WebSocket.<anonymous> (C:\projects\agent\node_modules\@secret-agent\core\server\index.js:81:35)
    at WebSocket.emit (node:events:365:28)
    at Receiver.receiverOnMessage (C:\projects\agent\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (node:events:365:28)
------REMOTE CORE---------------------------------
    at Object.<anonymous> (C:\projects\agent\node_modules\commons\TypeSerializer.ts:63:28)
    at JSON.parse (<anonymous>)
    at Function.parse (C:\projects\agent\node_modules\commons\TypeSerializer.ts:24:17)
    at WebSocket.<anonymous> (C:\projects\agent\node_modules\client\connections\RemoteConnectionToCore.ts:67:42)
    at WebSocket.emit (node:events:365:28)
    at Receiver.receiverOnMessage (C:\projects\agent\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (node:events:365:28)
    at Receiver.dataMessage (C:\projects\agent\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\projects\agent\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\projects\agent\node_modules\ws\lib\receiver.js:143:22)
------CONNECTION----------------------------------
    at new Resolvable (C:\projects\agent\node_modules\commons\Resolvable.ts:17:18)
    at Object.createPromise (C:\projects\agent\node_modules\commons\utils.ts:39:10)
    at RemoteConnectionToCore.createPendingResult (C:\projects\agent\node_modules\client\connections\ConnectionToCore.ts:324:31)
    at RemoteConnectionToCore.internalSendRequestAndWait (C:\projects\agent\node_modules\client\connections\ConnectionToCore.ts:251:43)
    at RemoteConnectionToCore.sendRequest (C:\projects\agent\node_modules\client\connections\ConnectionToCore.ts:154:17)
    at Object.cb (C:\projects\agent\node_modules\client\lib\CoreCommandQueue.ts:37:26)
    at Queue.next (C:\projects\agent\node_modules\commons\Queue.ts:79:19)
------CORE COMMANDS-------------------------------
    at Queue.run (C:\projects\agent\node_modules\commons\Queue.ts:32:19)
    at CoreCommandQueue.run (C:\projects\agent\node_modules\client\lib\CoreCommandQueue.ts:36:8)
    at CoreTab.goto (C:\projects\agent\node_modules\client\lib\CoreTab.ts:83:36)
    at Tab.goto (C:\projects\agent\node_modules\client\lib\Tab.ts:140:36)
    at C:\projects\agent\client.js:68:3

--------------------------------------------------
------agent1622540857946--------------------------
------d3676f20-c2c1-11eb-97ba-a1606b128280--------
-------------------------------------------------- {`

**Comment by janisblaus** [comment] 2021-06-01 10:44
Just noted that this same problem is there when not using connection to core, but executing xpath.

Here is full code example

`const {Agent,XPathResult} = require('secret-agent');

const fs = require('fs');

let title;

(async () => {

  //const date = new Date().getTime();
  const date = 1622540857946;

  const agentConfig = {
    humanEmulatorId: 'ghost',
    name: `Agent${date}`,
    showReplay: true,
    //upstreamProxyUrl: 'http://username:password@proxy.com:80',
    /*connectionToCore: {
      host: '127.0.0.1:7007',
    }*/
  };

  

  try{
    const rawProfileJson = fs.readFileSync(`cookies/${date}.json`, 'utf-8');

    if( rawProfileJson.length ){
      agentConfig.userProfile = JSON.parse(rawProfileJson); // { cookies: { sessionId: 'test' }}  
    }
  } catch(e){

  }


  const agent = await new Agent(agentConfig);

  await agent.goto('https://google.com/');

  await agent.waitForPaintingStable();

  title = await agent.document.title;

  console.log(`Domain loaded - ${title}`);

  await sleep(2);

 /**/
  try{
    const result = await agent.document.evaluate(
    '/html/body/div[2]/div[2]/div[3]/span/div/div/div[3]/button[2]',
      agent.document,
      null,
      XPathResult.FIRST_ORDERED_NODE_TYPE,
      null,
    );

    await agent.waitForElement(result.singleNodeValue, { waitForVisible: true, timeout: 10 });

    await result.singleNodeValue.click();
  } catch(e){
    console.log('no confirmation window found');
  }

  await sleep(2);


  await agent.goto('https://twitter.com/');

  await agent.waitForPaintingStable();

  title = await agent.document.title;

  console.log(`Domain loaded - ${title}`);

  await sleep(2);


  await agent.goto('https://facebook.com/');

  await agent.waitForPaintingStable();

  title = await agent.document.title;

  console.log(`Domain loaded - ${title}`);

  const latestUserProfile = await agent.exportUserProfile();

  fs.writeFileSync(`cookies/${date}.json`, JSON.stringify(latestUserProfile, null, 2));

  await agent.close();

})().catch(console.log);

async function sleep(timeMin) {
    return new Promise(res => {
        setTimeout(res, timeMin * 1000);
    });
}`

**Comment by blakebyrnes** [comment] 2021-06-01 13:33
Thanks for the report. Is it possible to share your session database for either of these scripts?

**Comment by janisblaus** [comment] 2021-06-01 13:51
Sure, project dir and session files attached. 
[project.zip](https://github.com/ulixee/secret-agent/files/6576683/project.zip)
[secret-agent.zip](https://github.com/ulixee/secret-agent/files/6576685/secret-agent.zip)

**Comment by blakebyrnes** [comment] 2021-06-04 13:03
It looks like this is being caused by the DNS server disconnecting and us not handling it (id=64 in SessionLogs). We resolved in #245 but haven't been able to do a build while we're fixing the plugin architecture. Let's keep this open and test once we're able to put out a new release.

**Comment by janisblaus** [comment] 2021-06-04 13:51
> once we're able to put out a new release.
neat! looking forward to it 😊

**Comment by blakebyrnes** [comment] 2021-06-29 12:46
@janisblaus this is working for me. Are you seeing better results?

**Comment by janisblaus** [comment] 2021-07-05 09:18
> @janisblaus this is working for me. Are you seeing better results?

Sorry for the late reply, will dive into testing your project again soon! :) Thank you!!

**Comment by blakebyrnes** [comment] 2021-07-14 14:54
@janisblaus You test this out at all yet?

**Closed** 2021-07-29 14:47 UTC
