### ISSUE TITLE
lauching multiple instance not working

### ISSUE THREAD

**Issue by lorenzo-alfieri-impex** [ulixee/secret-agent#178] opened 2021-02-26 15:13 UTC
Hi, i am working on a projet where we query a lot of different website. The issue i have is when i want to launch multiple instance of secret agent at the same time.

TLDR: I want to have a function where i send an array of url, and get the plain html of this website after js compute, then send back all the html in an array to an higher function to do only one insert. I tried every possible way i see and none work.

Long version :

So i just tried to launch an async func and hopped the instance of secret agent will be killed each time and a new one woulb be created, but it seem snot because i got this error :

```
2021-02-26T12:57:53.802Z ERROR [......../node_modules/@secret-agent/core/index] UnhandledErrorOrRejection {
  clientError: 'Error: aborted',
  context: {},
  sessionId: null,
  sessionName: undefined
} Error: aborted
    at connResetException (node:internal/errors:642:14)
    at Socket.socketCloseListener (node:_http_client:414:27)
    at Socket.emit (node:events:390:22)
    at Pipe.<anonymous> (node:net:665:12) {
  code: 'ECONNRESET'
}
```

Followed after by :
```
Error connecting to core {
  error: 'Error: connect ECONNREFUSED 127.0.0.1:58443',
  context: {},
  sessionId: null,
  sessionName: undefined
} Error: connect ECONNREFUSED 127.0.0.1:58443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 58443
}
Error: connect ECONNREFUSED 127.0.0.1:58443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1137:16)
------CORE COMMANDS------------------------------- 
    at CoreCommandQueue.run (...../node_modules/client/lib/CoreCommandQueue.ts:43:14)
    at RemoteConnectionToCore.createSession (...../node_modules/client/connections/ConnectionToCore.ts:138:49)
    at SessionConnection.connectSession (...../node_modules/client/lib/Agent.ts:382:36)
    at SessionConnection.get coreSession [as coreSession] (..../node_modules/client/lib/Agent.ts:312:17)
    at Agent.then (...../node_modules/client/lib/Agent.ts:295:46)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

i am using     "secret-agent": "^1.3.1-alpha.1" on a mac, and this is what my code to spawn instance look like (this is in an async func)

```
const { Agent } = require("secret-agent");
      let response = null;
      let agent = await new Agent();

      try {
        response = await (await agent.goto(url, 60000)).text();
        await agent.close();
      } catch (e) {
        console.log(e);
        await agent.close();
        if (response === null) return "";
      }
```

I also tried with tabs, to use agent.waitForNewTab(), but it just freeze on the first goto and stop there after timeout.

Lastly i tried with handler like this : 

```
let result = [];
const handleGetData = async (agent, dataset) => {
  result.push(await getData(agent, dataset));
};

const scrap = async (urlArray) => {
  const handler = new Handler();

  urlArray.map((url) => {
    return handler.dispatchAgent(handleGetData, { url });
  });

  await handler.waitForAllDispatches();
  await handler.close();

  console.log(result);
```
And i sent it 10 url, but only got one result before waitForAllDispatches ended.

So what am i doing wrong here ?

**Comment by lorenzo-alfieri-impex** [comment] 2021-03-08 11:11
Hi sorry i just saw the notification ...

i dont know why the formating is weird, so i give you the complete function with explanation on how this code work.

I have a table sql with urls i want to scrap. So i query this big table and extract urls i want to scrap, then create an array of it and send it to my function. I use handler since it seems to be the best way to do what i want, and all i want is row html in text : 

`const scrap = async (urlArray) => {
const handler = new Handler();
let result = [];
async function getHtml(agent, dataset) {
const ressource = await agent.goto(dataset.link);
result.push(await ressource.text());
}
for (const link of urlArray) {
handler.dispatchAgent(getHtml, {
link,
});
}
await handler.waitForAllDispatches();
await handler.close();
console.log(result);
}
`
I tried to use space and new line but formating dont work when i do sorry.

This return this error : 
`UnhandledRejection {
  error: "TypeError: Cannot read property 'toString' of null",
  context: {},
  sessionId: null,
  sessionName: undefined
} TypeError: Cannot read property 'toString' of null`

Both url sent (i only sent 2) are valid i checked it multiple time, and they work well, no 404, no error.
If i send only one url, i got the same result.

I also printed ressource,  and got this : 
`Resource {
  url: [Getter],
  isRedirect: [Getter],
  type: [Getter],
  request: [Getter],
  response: [Getter],
  data: [Getter],
  json: [Function: json],
  text: [Function: text]
}
`

**Comment by blakebyrnes** [comment] 2021-03-09 22:03
I think you have to use 3 ticks to get the formatting to stick.

I'm not able to reproduce locally. It seems to work as expected when I feed it these urls: 
```
scrap(['https://ulixee.org','https://dataliberationfoundation.org','https://secretagent.dev']).catch(console.log);
```

There's a small database that logs activity that should help troubleshoot. If you're comfortable sending, it would be really helpful. Location is `/private/tmp/.secret-agent/` on a mac, and each UUID is a different session.

**Comment by lorenzo-alfieri-impex** [comment] 2021-03-10 14:10
Hi, i tried with your url it works, but when i use mine, the session replay show the web site as expected, but whne i await the agent.document i got undefined.

I am not sure how to see things from your db, there are multiple table and im not sure what im looking for to give you the info. so here is the url https://www.amazon.fr/boite-a-salade/s?k=boite+a+salade. I tried with amazon home page it work, i tried some other amazon page it works, but some dont and i dont know why. some other website have the same behavior too.

**Comment by blakebyrnes** [comment] 2021-03-10 15:44
Ok, that's helpful. Thanks! This will be fixed in the next release.

**Comment by lorenzo-alfieri-impex** [comment] 2021-03-10 15:53
Ok perfect, if you need anything tell me im happy to help, if not for those url everything work perfectly so far

**Closed** 2021-03-10 22:38 UTC
