### ISSUE TITLE
ERR_HTTP2_ERROR

### ISSUE THREAD

**Issue by dmzebrov** [ulixee/secret-agent#174] opened 2021-02-22 14:49 UTC
Got this error, while repeatedly going to (goto) url.

`2021-02-22T14:42:21.608Z ERROR [/var/www/***/node_modules/@secret-agent/core/index] UnhandledError(fatal) {
  clientError: 'Error [ERR_HTTP2_ERROR]: Protocol error',
  context: {},
  sessionId: null,
  sessionName: undefined
} Error [ERR_HTTP2_ERROR]: Protocol error
    at Http2Session.onSessionInternalError (internal/http2/core.js:749:26) {
  code: 'ERR_HTTP2_ERROR',
  errno: -505
}`

If I try to close Agent instance and then create new to go to url, got this error:

`2021-02-22T14:42:21.811Z ERROR [/var/www/***/node_modules/@secret-agent/client/connections/ConnectionFactory] Error connecting to core {
  error: 'Error: connect ECONNREFUSED 127.0.0.1:37991',
  context: {},
  sessionId: null,
  sessionName: undefined
} Error: connect ECONNREFUSED 127.0.0.1:37991
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 37991
}`

**Comment by dmzebrov** [comment] 2021-02-23 10:06
It seems that the frequency of this error is directly related to the processing power of the hardware.

**Comment by blakebyrnes** [comment] 2021-02-23 14:53
@dmzebrov do you see this on any url? Or is it one in particular? Are you still on node 14 on mac 11.2?

**Comment by blakebyrnes** [comment] 2021-02-23 17:12
Also, which version of SecretAgent are you seeing this on?

**Comment by dmzebrov** [comment] 2021-02-23 18:50
@blakebyrnes I tested two urls, including myip.com, error appears on both. Also, I tested same code on macOS 11.2.1 (node v14.15.1) and Ubuntu 18.04 (node v14.15.0). On macOS error appears much less often than on Ubuntu. I may be wrong but I think it is because of difference in compute power. In both tests I use Secret Agent v1.3.1-alpha.1.

**Comment by blakebyrnes** [comment] 2021-02-23 18:52
Ok, thanks. Will poke around in Ubuntu too. Node's http2 implementation relies heavily on libnghttp2, so it's possible there are platform differences.

**Comment by dmzebrov** [comment] 2021-02-23 18:56
Thank you, I'll wait! If you need anything from me - I'll be glad to help.

**Comment by blakebyrnes** [comment] 2021-02-23 18:57
Thanks. Is it possible to share your script? I haven't managed to reproduce yet.

**Comment by dmzebrov** [comment] 2021-02-23 19:11
Sure, here it is:

[test.txt](https://github.com/ulixee/secret-agent/files/6031333/test.txt)

**Comment by blakebyrnes** [comment] 2021-02-23 19:19
Thanks! How many times did you loop before it throws the errors above?

**Comment by dmzebrov** [comment] 2021-02-23 19:31
It is pretty random, but if you start, for example, 5 instances of the same node process - it appears near immediately in at least one of them. But even with 1 instance of node process it appears at some point.

**Comment by blakebyrnes** [comment] 2021-02-23 21:03
I'm still not seeing that specific error, but I've seen frequent errors on myip.com that seem to come from https://us-u.openx.net/ requests.

```
Error [ERR_HTTP2_STREAM_ERROR]: Stream closed with error code NGHTTP2_INTERNAL_ERROR
    at ClientHttp2Stream._destroy (internal/http2/core.js:2189:13)
    at ClientHttp2Stream.destroy (internal/streams/destroy.js:39:8)
    at Http2Stream.onStreamClose (internal/http2/core.js:510:12) {
  code: 'ERR_HTTP2_STREAM_ERROR'
}
```

**Comment by dmzebrov** [comment] 2021-02-23 21:20
Please, try as I mentioned in previous message (with multiple node server instances running in parallel) and with street-beat.ru

**Comment by dmzebrov** [comment] 2021-02-24 07:03
On street-beat it seems to occur more often

**Comment by blakebyrnes** [comment] 2021-02-24 22:04
I've tried the street-beat example too, but can't reproduce the exact error you're seeing. My connection to street-beat from here is very slow though, so that might have something to do with what you're seeing. I did find an error that we're not handling a little better that will hopefully resolve your issue. Can you let me know once we put out our new release?

**Comment by dmzebrov** [comment] 2021-02-25 05:09
Your slow connection is most definitely the reason why you can't reproduce the error with street-beat. At the same time you should be able to reproduce the error with myip, but it can take some time. Probably, you can try to restart node once in the minute by hands, seems like it increases the chance for error to occur.

Anyway I will let you know if the error is resolved!

**Comment by blakebyrnes** [comment] 2021-03-12 13:43
@dmzebrov Whenever you get the chance, would love to know if this has been resolved with the new version.

**Comment by dmzebrov** [comment] 2021-03-16 11:10
@blakebyrnes I still got this error: 

`ERROR [/var/www/*my_path*/node_modules/@secret-agent/mitm-socket/index] SocketConnectDriver.SocketError {
   error: 'Error [ERR_HTTP2_ERROR]: Protocol error',
   socketPath: '/tmp/sa-0b7e5200-8647-11eb-b370-95a26bfb8643.sock',
   host: '87.240.139.194',
   clientHello: 'Chrome83',
   context: { sessionId: 'ff5c64d0-8646-11eb-b370-95a26bfb8643' },
   sessionId: 'ff5c64d0-8646-11eb-b370-95a26bfb8643',
   sessionName: 'default-session-12'
 } Error [ERR_HTTP2_ERROR]: Protocol error
    at Http2Session.onSessionInternalError (internal/http2/core.js:749:26) {
  code: 'ERR_HTTP2_ERROR',
   errno: -505
 }`

But now it doesn't make the whole process hang. So I guess this issue is at least partly resolved. Thank you!

**Comment by blakebyrnes** [comment] 2021-03-23 20:21
I'm going to close this for now if it's not impacting your code. You should see these errors disappear in the new version.

**Closed by blakebyrnes** 2021-03-23 20:21 UTC
